language: node_js
node_js: stable

sudo: false

addons:
  firefox: "39.0"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/NathanWalker/angular-seed-advanced/npm-debug.log

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    npm run build.prod
    cd ./dist/prod
    ls
    git init
    git add .
    git -c user.name='shaggyshelar' -c user.email='shaggy.shelar@gmail.com' commit -m AutoDeployFromTravis
    git push -f -q https://$GITHUB_API_KEY@github.com/shaggyshelar/Temp.git master
  fi

branches:
  only: framework

notifications:
  email: true
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories: node_modules

script:
  - npm run test

