language: node_js
node_js: stable

sudo: false

addons:
  firefox: "39.0"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/NathanWalker/angular-seed-advanced/npm-debug.log

after_success:
- echo "Starting production build..."
- npm run build.prod
- echo "Finished production build..."
- cd ./dist/prod
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add deploy ssh://5809e8412d5271cc910000fe@sh-sagarshelar.rhcloud.com/~/git/sh.git/
- git push deploy
- echo "Deployment Sucessfulllllllllllllll...."

branches:
  only: framework

notifications:
  email: true
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

cache:
  directories: node_modules

script:
  - npm run test

deploy:
  provider: openshift
  user: shaggyshelar
  password:
    secure: VZzgGOKWPjwmLTE+pIy6hwWI0ZPxD1V5TqEEOqajZKX26xz8mWhQLXEmcy6LInYhj/9phVxlkQE1xN5DsHAApykAMDyFbplVAlnbtKWEJWxI2MFsNgYhXlCZZjNUGuC3bM7QCntm89mfycSdgnNBgxIy33tuJ6mZ5XMVJAYBNhKjFkfRTSTAywT+hM2WitoSr7pncPqRWs4Ddy4alD1+iAVk6CrVoJEd/U9GfcApT+G0uP5aQU2yxKTsUNE/n0ffBgJWMtzDTIGwhKAdIzTEhF5sMS07Ht/dNpxunFC44aEJOMs8MBkpSfYsXTz5ZFa/yQswQOxDtNFib740JFSy7BSGJlDNyexTUIqaPBzd13KFlPiBTjnMtjaia4GLutvqCTcm+9F2o0rjzgYpOfCn72FO7ljV3oP468zJWkMPBc4FCnBpQ/LC9Baq+BdkS+gQXO9xZ9x1og9iTpXI4UXsqe6XFQW4vi7t4hJeGDH9Q5o1v8zx6LJnE8cxULLStd0YsjbXoPzsagMjMvarl4afPElDxxbM51DTgjEVNpxVuw1TZozNljP+YoQ79xrglWnlEEAVDZm+zPWeOgwrSx783ut8/VieC1huokE5UfiIFBulP737PPLjpElxedJxGYZlEMegcqvbE7oO6UMRmQD/R9i3dBZMVL8+2eEvCRNKvys=
  app: sh
  domain: sagarshelar
